name: profit_mart
description: A new Flutter project.

publish_to: 'none'
#
#version: 1.0.0+1
#
#environment:
#  sdk: '>=2.19.4 <3.0.0'
#
#dependencies:
#  shared_preferences: ^2.0.6
#  http: ^0.13.5
#  url_launcher:
#
#  flutter:
#    sdk: flutter
#
#  cupertino_icons: ^1.0.2
#  retrofit: ^3.3.1
#  intl: ^0.16.1
#  json_serializable: ^6.6.2
#
#
#dev_dependencies:
#  flutter_lints: ^2.0.0
#  retrofit_generator: '>=4.0.0 <5.0.0'
#  build_runner: '>2.3.0 <4.0.0'
#  flutter_native_splash: ^2.2.19
#  url_launcher: ^6.1.10
#  flutter_test:
#    sdk: flutter
#flutter_native_splash:
#
#  flutter_lints: ^2.0.0
#
#flutter:
#
#  uses-material-design: true
#
#  assets:
#    - assets/
#


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  get:
  flutter_pdfview: ^1.0.2
  shared_preferences: ^2.0.6
  flutter_cache_manager: ^3.2.0
  http: ^0.13.5
  url_launcher:



  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.3.1
  #  intl: ^0.16.1
  intl: ^0.17.0
  json_serializable: ^6.6.2
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  firebase_database: ^10.2.1
  firebase_storage: ^11.2.1
  flutter_local_notifications: ^14.1.0
  #  cloud_firestore: ^4.7.1


dev_dependencies:
  #  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  flutter_native_splash: ^2.2.19
  url_launcher: ^6.1.10
  flutter_test:
    sdk: flutter
flutter_native_splash:
#  color: "#ffffff"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/icon.png"


  #  min_sdk_android: 21
  #  web:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  #  windows:
  #    generate: true
  #    image_path: "path/to/image.png"
  #    icon_size: 48 # min:48, max:256, default: 48
  #  macos:
  #    generate: true
  #    image_path: "path/to/image.png"


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg
